### ISSUE TITLE
能不能出一个启动教程，感谢

### ISSUE THREAD

**Issue by cyilu** [LibiChai/dcron#10]
如题，感谢

**Comment by cyilu** [comment]
我出现了一个错误
`go: github.com/gomodule/redigo@v2.0.0+incompatible: Get "https://proxy.golang.org/github.com/gomodule/redigo/@v/v2.0.0+incompatible.mod": dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by LibiChai** [comment]
@cyilu 这是因为你本地 go mod 的代理配置成了 proxy.golang.org ，golang.org 国内需要搭梯子。
建议使用指令切换到阿里云的 goproxy 即可。 
``` 
export GOPROXY=https://mirrors.aliyun.com/goproxy/ 
```
